version: '3.8'
services:
  string-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: string-api
    ports:
      - 5555:5555
    depends_on:
      - db
      - redis
    volumes:
      - ./:/string_api
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=string_db
      - POSTGRES_PASSWORD=string_password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis-node-0:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - REDIS_NODES=redis-node-0
    volumes:
      - redis-node-0:/node/data
  redis:
    image: bitnami/redis-cluster:latest
    restart: always
    depends_on:
      - redis-node-0
    environment:
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - REDIS_NODES=redis-node-0
      - CLUSTER_CREATOR=yes  
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local
  redis-node-0:
    driver: local
