version: '3.8'
services:
  string-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: string-api
    ports:
      - 5555:5555
    depends_on:
      - db
      - redis
    volumes:
      - ./:/string-api
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=string_db
      - POSTGRES_PASSWORD=string_password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local
