-------------------------------------------------------------------------
-- +goose Up

-------------------------------------------------------------------------
-- CONTACT_PLATFORM -----------------------------------------------------
CREATE TABLE contact_platform (
  contact_id UUID REFERENCES contact (id),
  platform_id UUID REFERENCES platform (id)
);

CREATE UNIQUE INDEX contact_platform_contact_id_platform_id_idx ON contact_platform(contact_id, platform_id);

-------------------------------------------------------------------------
-- DEVICE_INSTRUMENT ----------------------------------------------------
CREATE TABLE device_instrument (
  device_id UUID REFERENCES device (id),
  instrument_id UUID REFERENCES instrument (id)
);

CREATE UNIQUE INDEX device_instrument_device_id_instrument_id_idx ON device_instrument(device_id, instrument_id);

-------------------------------------------------------------------------
-- TX_LEG ---------------------------------------------------------------
CREATE TABLE tx_leg (
  id UUID PRIMARY KEY NOT NULL DEFAULT UUID_GENERATE_V4(), -- unique identifier for the TX leg which we generate
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, -- initial timestamp of creation
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, -- timestamp whenever this tx_leg is updated
  -- TIMESTAMP:
  -- For CC send = auth timestamp
  -- For CC receive = capture timestamp
  -- For EVM send = txid generation timestamp
  -- For EVM receive = txid confirmation timestamp 
  timestamp TIMESTAMP WITH TIME ZONE, 
  amount TEXT DEFAULT '', -- Quantity of financial asset in Asset wei
  value TEXT DEFAULT '', -- Quantity of financial asset in [USD wei (6 digits precision)]
  asset_id UUID REFERENCES asset (id), -- ID of table entry of Asset (for USD, ETH, AVAX etc)
  -- USER_ID:
  -- For CC send = id that correlates to the end-user in our user table
  -- For CC receive = id that correlates to the STRING entry in our user table
  -- For EVM send = id that correlates to the STRING entry in our user table
  -- For EVM receive = NULL if recipient is not an end user, or id that corrlates to end-user recipient in our user table
  user_id UUID REFERENCES string_user (id) DEFAULT NULL,
  -- INSTRUMENT_ID:
  -- For CC send = id that correlates to the users credit card in our Instrument table
  -- For CC receive = id that correlates to STRING bank account in our Instrument table
  -- For EVM send = id that correlates to our wallet address in our Instrument table
  -- For EVM receive = id that correlates to RECIPIENTS wallet in our Instrument table, regardless of if they are a user
  instrument_id UUID NOT NULL REFERENCES instrument (id)
);

CREATE OR REPLACE TRIGGER update_tx_leg_updated_at
    BEFORE UPDATE
    ON tx_leg
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

-------------------------------------------------------------------------
-- TRANSACTION ----------------------------------------------------------
CREATE TABLE transaction (
  id UUID PRIMARY KEY NOT NULL DEFAULT UUID_GENERATE_V4(), -- unique idenfier for the transaction which we generate
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, -- time transaction entry was initially created
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, -- time transaction entry was last updated, including adding tags
  type TEXT DEFAULT '', -- enum [fiat-to-crypto, crypto-to-fiat] (these types may eventually have subtypes, ie NFT_MINT)
  status TEXT DEFAULT '', --enum State of the transaction in the /transact endpoint
  tags JSONB DEFAULT '{}'::JSONB, -- Empty but will be used for Unit21.  These are key-val pairs for flagging transactions
  device_id UUID REFERENCES device (id), -- id that correlates to end-users device in our Device table, we get the data from fingerprint.com -- TODO: Get this with fingerprint integration
  ip_address TEXT DEFAULT '', -- we get this data from fingerprint.com, whatever is being used at time of transaction
  platform_id UUID REFERENCES platform (id), -- id that correlates to CUSTOMER in our Platform table (ie gamefi.xyz)
  transaction_hash TEXT DEFAULT '', -- EVM/network TX ID after it is generated by executor
  network_id UUID NOT NULL REFERENCES network (id), -- id that correlates to the Network (Chain) in our Network table
  network_fee TEXT DEFAULT '', -- The true amount of gas in wei that was used to facilitate the transaction
  contract_params JSONB DEFAULT '{}'::JSONB, -- The parameters passed into the EVM function call passed into the endpoint
  contract_func TEXT DEFAULT '', -- The declaration of the EVM function call passed into the endpoint
  transaction_amount TEXT DEFAULT '', -- The cost in native token wei of the transaction passed into the endpoint
  origin_tx_leg_id UUID REFERENCES tx_leg (id) DEFAULT NULL, -- id that correlates to the Leg of the CC send in our Leg table
  receipt_tx_leg_id UUID REFERENCES tx_leg (id) DEFAULT NULL, -- id that correlates to the Leg of the CC receive in our Leg table
  response_tx_leg_id UUID REFERENCES tx_leg (id) DEFAULT NULL, -- id that correlates to the leg of the EVM send in our Leg table
  destination_tx_leg_id UUID REFERENCES tx_leg (id) DEFAULT NULL, -- id that correlates to the leg of the EVM receive in our Leg table
  processing_fee TEXT DEFAULT '', -- CC (ie checkout) processing fee in (USD/???) wei
  processing_fee_asset UUID REFERENCES asset (id), -- CC processing fee asset id in asset table (ie id for USD)
  string_fee TEXT DEFAULT '' -- Amount in (USD!) wei that we charged to facilitate this transaction, likely always will be USD
);

CREATE OR REPLACE TRIGGER update_transaction_updated_at
    BEFORE UPDATE
    ON transaction
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

-------------------------------------------------------------------------
-- +goose Down

-------------------------------------------------------------------------
-- TRANSACTION ----------------------------------------------------------
DROP TRIGGER IF EXISTS update_transaction_updated_at ON transaction;
DROP TABLE IF EXISTS transaction;

-------------------------------------------------------------------------
-- TX_LEG ---------------------------------------------------------------
DROP TRIGGER IF EXISTS update_tx_leg_updated_at ON tx_leg;
DROP TABLE IF EXISTS tx_leg;

-------------------------------------------------------------------------
-- DEVICE_INSTRUMENT ----------------------------------------------------
DROP TABLE IF EXISTS device_instrument;

-------------------------------------------------------------------------
-- CONTACT_PLATFORM -----------------------------------------------------
DROP TABLE IF EXISTS contact_platform;