on:
  pull_request:
    branches:
      - develop 
name: run tests
env:
  BASE_URL: http://localhost:5555/ 
  ENV: local
  PORT: 5555
  STRING_HOTWALLET_ADDRESS: ${{ secret.HOT_WALLET }}
  COINGECKO_API_URL: ${{ env.COINCAP_API_URL }}
  COINCAP_API_URL: ${{ env.COINCAP_API_URL }}
  OWLRACLE_API_URL: ${{ env.OWLRACLE_API_KEY }}
  OWLRACLE_API_KEY: ${{ secret.OWLRACLE_API_KEY }}
  OWLRACLE_API_SECRET: ${{ secret.OWLRACLE_API_SECRET }}     
  AWS_KMS_KEY_ID: ${{  secret.AWS_KMS_KEY_ID }}          
  CHECKOUT_PUBLIC_KEY: ${{ secret.CHECKOUT_PUBLIC_KEY }}    
  CHECKOUT_SECRET_KEY: ${{ secret.CHECKOUT_SECRET_KEY }}
  CHECKOUT_ENV: ${{ env.CHECKOUT_ENV }}            
  EVM_PRIVATE_KEY: ${{ secret.EVM_PRIVATE_KEY }}         
  DB_NAME: stringdb                 
  DB_USERNAME: string       
  DB_PASSWORD: string          
  DB_HOST: localhost              
  DB_PORT: 5432                
  REDIS_PASSWORD: password    
  REDIS_HOST: localhost          
  REDIS_PORT: 6379            
  JWT_SECRET_KEY: ${{ secret.JWT_SECRET_KEY }}          
  UNIT21_API_KEY: ${{ secret.UNIT21_API_KEY }}          
  UNIT21_ENV: sandbox              
  UNIT21_ORG_NAME: string         
  UNIT21_RTR_URL: ${{ env.UNIT21_RTR_URL }}          
  TWILIO_ACCOUNT_SID: ${{ secret.TWILIO_ACCOUNT_SID }}      
  TWILIO_AUTH_TOKEN: ${{ secret.TWILIO_AUTH_TOKEN }}      
  TWILIO_SMS_SID: ${{ secret.TWILIO_SMS_SID }}         
  TEAM_PHONE_NUMBERS: ${{ secret.TEAM_PHONE_NUMBERS }}      
  STRING_ENCRYPTION_KEY: ${{ secret.STRING_ENCRYPTION_KEY }}   
  SENDGRID_API_KEY: ${{ secret.SENDGRID_API_KEY }}        
  FINGERPRINT_API_KEY: ${{ secret.FINGERPRINT_API_KEY }}     
  FINGERPRINT_API_URL: ${{ env.FINGERPRINT_API_URL }}     
  STRING_INTERNAL_ID: ${{ secret.STRING_INTERNAL_ID }}      
  STRING_WALLET_ID: ${{ secret.STRING_WALLET_ID }}        
  STRING_BANK_ID: ${{ secret.STRING_BANK_ID }}          
  SERVICE_NAME: string-api            
  DEBUG_MODE: false              
  AUTH_EMAIL_ADDRESS: ${{ env.AUTH_EMAIL_ADDRESS }}      
  RECEIPTS_EMAIL_ADDRESS: ${{ env.RECEIPTS_EMAIL_ADDRESS }}  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
      - name: Run golangci-lint
        run: golangci-lint run --version --verbose --out-format=github-actions

  test:
    strategy:
      matrix:
        go-version: [1.19]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{  matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: ${{  matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./pkg/... -v -covermode=count

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: |
          go test ./pkg/... -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          path-to-lcov: coverage.lcov
